# Generated by Django 5.1.6 on 2025-02-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(max_length=20)),
                ('total_price', models.FloatField()),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
